2020-08-20 17:30:28,074 ERROR: Exception on /api/object [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 288, in object_change_location
    movement = Movement(oid = the_object, operation_id=Operation.query.filter_by(name=row['operation']).first().id, placement_id =Placement.query.filter_by(placement_name=row['placement']).first().id, previous_placement_id=placement_id, description=row['movement'], operation_time=datetime.datetime.utcnow(), asinfo=row['movement_info'])
NameError: name 'placement_id' is not defined
2020-08-20 17:33:50,655 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:35:06,326 ERROR: Exception on /api/object [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 288, in object_change_location
    placement_id=Object.query.join(Movement).order_by(Movement.operation_time.desc()).first().placement_id
AttributeError: 'Object' object has no attribute 'placement_id'
2020-08-20 17:39:00,974 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:39:08,360 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:39:31,307 ERROR: Exception on /api/object [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 289, in object_change_location
    movement = Movement(oid = the_object, operation_id=Operation.query.filter_by(name=row['operation']).first().id, placement_id =Placement.query.filter_by(placement_name=row['placement']).first().id, previous_placement_id= placement_id, description=row['movement'], operation_time=datetime.datetime.utcnow(), asinfo=row['movement_info'])
  File "<string>", line 4, in __init__
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\sqlalchemy\orm\state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\sqlalchemy\orm\state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 839, in _declarative_constructor
    raise TypeError(
TypeError: 'previous_placement_id' is an invalid keyword argument for Movement
2020-08-20 17:40:11,335 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:42:10,341 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:44:05,481 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:44:28,712 ERROR: Exception on /api/report/motion [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 239, in check_placement
    previous_placement = Placement.query.filter_by(id=object_reports.from_placement_id).first().placement_name
AttributeError: 'AppenderBaseQuery' object has no attribute 'from_placement_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 248, in get_report_motion
    data =  [{
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 252, in <listcomp>
    "previous_placement":  check_placement(object_report),
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 241, in check_placement
    except NoneType:
NameError: name 'NoneType' is not defined
