2020-08-20 17:44:43,030 ERROR: Exception on /api/report/motion [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 239, in check_placement
    previous_placement = Placement.query.filter_by(id=object_reports.from_placement_id).first().placement_name
AttributeError: 'AppenderBaseQuery' object has no attribute 'from_placement_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 248, in get_report_motion
    data =  [{
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 252, in <listcomp>
    "previous_placement":  check_placement(object_report),
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 241, in check_placement
    except NoneType:
NameError: name 'NoneType' is not defined
2020-08-20 17:44:43,239 ERROR: Exception on /api/report/motion [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 233, in get_report_motion
    object_reports = Object.query.filter_by(id = object_id).first().movements
AttributeError: 'NoneType' object has no attribute 'movements'
2020-08-20 17:44:50,972 ERROR: Exception on /api/report/motion [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 239, in check_placement
    previous_placement = Placement.query.filter_by(id=object_reports.from_placement_id).first().placement_name
AttributeError: 'AppenderBaseQuery' object has no attribute 'from_placement_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 248, in get_report_motion
    data =  [{
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 252, in <listcomp>
    "previous_placement":  check_placement(object_report),
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 241, in check_placement
    except NoneType:
NameError: name 'NoneType' is not defined
2020-08-20 17:45:21,923 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:45:34,168 ERROR: Exception on /api/report/motion [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 248, in get_report_motion
    data =  [{
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 252, in <listcomp>
    "previous_placement":  Placement.query.filter_by(id=object_reports.from_placement_id).first().placement_name,
AttributeError: 'AppenderBaseQuery' object has no attribute 'from_placement_id'
2020-08-20 17:46:43,922 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
2020-08-20 17:46:47,233 ERROR: Exception on /api/report/motion [POST] [in c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "c:\users\1\inventory2\inventory1\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 248, in get_report_motion
    data =  [{
  File "C:\Users\1\inventory2\inventory1\app\api\commodity.py", line 252, in <listcomp>
    "previous_placement":  check_placement(),
TypeError: check_placement() missing 1 required positional argument: 'object_report'
2020-08-20 17:47:15,963 INFO: Inventory1 startup [in C:\Users\1\inventory2\inventory1\app\__init__.py:42]
